import {
  rotationDefault,
  rotationNone,
  rotationToRightUp,
  rotationToRightDown,
  rotationToLeftDown,
  rotationToLeftUp,
  rotationToLeftUp2,
  rotationToCornersRightDown,
} from './rotations'

export const createPieceBox = (id, sprite, status) => [
  {
    id: id,
    x: 3,
    y: 0,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite,
    rotation: rotationNone(),
  },
  {
    id: id,
    x: 4,
    y: 0,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite,
    rotation: rotationNone(),
  },
  {
    id: id,
    x: 3,
    y: 1,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite,
    rotation: rotationNone(),
  },
  {
    id: id,
    x: 4,
    y: 1,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite,
    rotation: rotationNone(),
  },
]
