import {
  rotationDefault,
  rotationNone,
  rotationToRightUp,
  rotationToRightDown,
  rotationToLeftDown,
  rotationToLeftUp,
  rotationToLeftUp2,
  rotationToCornersRightDown,
} from './rotations'

export const createPieceT = (id, sprite, status) => [
  {
    id: id,
    x: 0,
    y: 0,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite,
    rotation: rotationToRightUp(),
  },
  {
    id: id,
    x: 1,
    y: 0,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite,
    rotation: rotationNone(),
  },
  {
    id: id,
    x: 2,
    y: 0,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite,
    rotation: rotationToLeftDown(),
  },
  {
    id: id,
    x: 1,
    y: 1,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite,
    rotation: rotationToLeftUp(),
  },
]
