import {
  rotationDefault,
  rotationNone,
  rotationToRightUp,
  rotationToRightDown,
  rotationToLeftDown,
  rotationToLeftUp,
  rotationToLeftUp2,
  rotationToCornersRightDown,
} from './rotations'

export const createPieceBox = (id, x, sprite, status) => [
  {
    id: id,
    x: x,
    y: 0,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite == '0' ? '0' : sprite,  
    rotation: rotationNone(),
  },
  {
    id: id,
    x: x+1,
    y: 0,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite == '0' ? '1' : sprite,  
    rotation: rotationNone(1,0),
  },
  {
    id: id,
    x: x,
    y: 1,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite == '0' ? '2' : sprite,  
    rotation: rotationNone(0,1),
  },
  {
    id: id,
    x: x+1,
    y: 1,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite == '0' ? '3' : sprite,  
    rotation: rotationNone(1,1),
  },
]
