import {
  rotationDefault,
  rotationNone,
  rotationToRightUp,
  rotationToRightDown,
  rotationToLeftDown,
  rotationToLeftUp,
  rotationToLeftUp2,
  rotationToCornersRightDown,
  rotationR1,
  rotationL1,
  rotationR1D1,
} from './rotations'

export const createPieceL = (id, x, sprite, status) => [
  {
    id: id,
    initialX: x,
    initialY: 1,
    x: x,
    y: 1,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite == '0' ? '0' : sprite,  
    rotation: rotationNone(),
  },
  {
    id: id,
    initialX: x,
    initialY: 0,
    x: x,
    y: 0,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite == '0' ? '1' : sprite,  
    rotation: rotationR1(),
  },
  {
    id: id,
    initialX: x+1,
    initialY: 0,
    x: x+1,
    y: 0,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite == '0' ? '2' : sprite,  
    rotation: rotationR1D1(),
  },
  {
    id: id,
    initialX: x,
    initialY: 2,
    x: x,
    y: 2,
    moveX: 0,
    moveY: 0,
    moveUpdate: false,
    status: status,
    gravityCounter: 0,
    sprite: sprite == '0' ? '3' : sprite,  
    rotation: rotationL1(),
  },
]
